### ISSUE TITLE
Home page, Book management(add, delete, update, search) and  Database

### ISSUE THREAD

**Issue by Sokmeak** [Sokmeak/Project-Library-Management-System#9]
Create a friendly interface in home page, and book management as well. After that store our data in database(MySQL).
<img width="933" alt="Homepage" src="https://github.com/Sokmeak/Project-Library-Management-System/assets/120242
<img width="882" alt="BookManagement" src="https://github.com/Sokmeak/Project-Library-Management-System/assets/120242475/4612696b-f44a-45e3-83e2-b65bb8384432">
475/5b53dcda-81d3-4b56-939c-e36cceb73a7c">

**Comment by Sokmeak** [comment]
Try your best!

**Comment by Vibaksanna** [comment]
I have completed my task.
